version: "3"

services:
  node:
    image: node:alpine
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - PORT=3000
      - MONGODB_URI=mongodb://mongo/database
      - JWT_SECRET=very_secure_password_1234567890
      - CLOUDINARY_API_KEY=
      - CLOUDINARY_API_SECRET=
      - CLOUDINARY_CLOUD_NAME=
    ports:
      - 8081:3000
    command: yarn dev
    links:
      - mongo

  mongo:
    image: mongo:latest

  mongo_express:
    image: mongo-express:latest
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_AUTH_DATABASE=accommodate
      - ME_CONFIG_MONGODB_AUTH_USERNAME=user
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
    links:
      - mongo
